package com.runway.dto;

public enum InsightType {
    CATEGORY_INCREASE,
    CATEGORY_DECREASE,
    TOP_CATEGORY,
    FASTEST_GROWING_CATEGORY,
    MERCHANT_FREQUENCY,
    MERCHANT_REPEATED_SPEND,
    SPENDING_PATTERN_WEEKDAY,
    SPENDING_PATTERN_WEEKEND,
    BUDGET_PACING,
    ANOMALY_UNUSUAL_EXPENSE
}
